openapi: 3.0.0
info:
  description: >-
    API Definition for Sample Seriver
  version: 0.1.0
  title: My Sample Service
servers:
  - url: 'http://localhost:8080'
paths:    
  '/pony':
    get:
      operationId: list
      parameters:
        - in: query
          name: pageQuery
          schema:
            type: object
            properties:
              offset:
                type: integer
                format: int32
              limit:
                type: integer
                format: int3
      responses:
        200:
          description: response
          content:
            application/json:
              schema:
                type: string        
  
                      
  '/example/api':              
    get:
      operationId: getListResults
      parameters:
        - name: integerParam
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 20
            format: int32
            default: 10
        - name: dateParam
          in: query
          required: false
          schema:
            type: string
            format: date
        - name: dateTimeParam
          in: query
          schema:
             type: string
             format: date-time
        - name: requiredQueryParam
          in: query
          required: true
          schema:
            type: string
        - name: formatParam
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/format'
      responses:
        200:
          description: response
          content:
            application/json:
              schema:
                type: string        
  
components:
  schemas:
    format:
      default: json
      description: response format
      enum:
      - json
      - csv
      type: string          